import { ColorResolvable } from "discord.js"

type Divisa = {
            id: string,
            nombre: string,
            iso: string,
            bandera: string,
            descripcion: string,
            color: ColorResolvable,
            gradient?: [ColorResolvable, ColorResolvable];
            gradientBox?: [ColorResolvable, ColorResolvable];
            img: string,
            ac: string,
            paises: string,
            simbolo: string,
            billetes: string,
            monedas: string,
            inflacion: string,
            emisor: string
        }

const divisas: Divisa[] = [
            {
                id: "dolar",
                nombre: "Dólar estadounidense",
                iso: "USD",
                bandera: "🇺🇸",
                descripcion: "El dólar estadounidense es la moneda oficial de los Estados Unidos y de varios países y territorios. Es la moneda más utilizada en el mundo y es ampliamente aceptada como medio de pago en todo el mundo.",
                color: "#43B581",
                gradient: ["#1e2a25", "#151a17"],
                gradientBox: ["#2a3d35", "#252f2a"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/903145945980604447/dolar3.png?ex=6988c0f5&is=69876f75&hm=e4ee0c63930532f4e00d712525e5eff67072083b66f0e8eba93193145cccc985",
                ac: "1792",
                paises: ":flag_us: :flag_ec: :flag_sv: :flag_pr: :flag_mx: :flag_pa: :flag_do: :flag_ht: :flag_tl:",
                simbolo: "$",
                billetes: "$1, $5, $10, $20, $50, $100",
                monedas: "$0.01, $0.05, $0.10, $0.25, $0.50, $1",
                inflacion: "2.8% (Febrero 2025)",
                emisor: "Reserva Federal de los Estados Unidos"
            },
            {
                id: "euro",
                nombre: "Euro",
                iso: "EUR",
                bandera: ":flag_eu:",
                descripcion: "El euro (€) es la moneda usada por las instituciones de la Unión Europea (UE), así como la moneda oficial de la eurozona, formada por 19 de los 27 Estados miembros de la UE. Además, 4 micro-Estados europeos tienen acuerdos con la Unión Europea para el uso del euro como moneda",
                color: "#5B9BD5",
                gradient: ["#1a2a3d", "#0f1a28"],
                gradientBox: ["#243a52", "#1d3045"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/913863513498333224/european-union_1.png",
                ac: "1 de enero de 2002",
                paises: ":flag_de: :flag_at: :flag_be: :flag_cy: :flag_sk: :flag_si: :flag_es: :flag_ee: :flag_fi: :flag_fr: :flag_gr: :flag_ie: :flag_it: :flag_lv: :flag_lt: :flag_lu: :flag_mt: :flag_nl: :flag_pt: :flag_ad: :flag_va: :flag_mc: :flag_sm: :flag_xk: :flag_me:" ,
                simbolo: "€",
                billetes: "€5, €10, €20, €50, €100, €200, €500",
                monedas: "€0,01, €0,02, €0,05, €0,10, €0,20, €0,50, €1, €2",
                inflacion: "2,3% (Febrero 2025)",
                emisor: "Banco Central Europeo"
            
            },
            {
                id: "real",
                nombre: "Real Brasilero",
                iso: "BRL",
                bandera: ":flag_br:",
                descripcion: "El real es la moneda de curso legal en Brasil y fuera de sus fronteras se le conoce como real brasileño. A partir de 2020, es la vigésima moneda más negociada en el mundo, la segunda en América Latina detrás de peso mexicano y la cuarta en el continente americano detrás del dólar estadounidense, el dólar canadiense y el peso mexicano",
                color: "#F4D03F",
                gradient: ["#1a2e1a", "#0f1c0f"],
                gradientBox: ["#2a4a2a", "#1f3a1f"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/1068375006784012288/BrazilMoney.png",
                ac: "1994",
                paises: ":flag_br:",
                simbolo: "R$",
                billetes: "R$2, R$5, R$10, R$20, R$50, R$100 y R$200",
                monedas: "R$0,01, R$0,05, R$0,10, R$0,25, R$0,50 y R$1",
                inflacion: "10.74% (2021)",
                emisor: "Banco Central do Brasil"
            }, {
                id: "yen",
                nombre: "Yen Japonés",
                iso: "JPY",
                bandera: ":flag_jp:",
                descripcion: "El yen es la moneda de Japón, muy valiosa en el mercado global, la tercera más importante tras el dólar y el euro. También se usa como reserva junto con otras monedas como el dólar y el euro, y en la numeración japonesa, las grandes cantidades se expresan en múltiplos de 10,000 (man, 万).",
                color: "#E74C3C",
                gradient: ["#2a1a1a", "#1a0f0f"],
                gradientBox: ["#3d2525", "#2f1c1c"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/913893648876331048/yenjapones3.png",
                ac: "10 de mayo de 1871",
                paises: ":flag_jp:",
                simbolo: "¥",
                billetes: "¥1000, ¥2000, ¥5000 y ¥10000",
                monedas: "¥1, ¥5, ¥10, ¥50, ¥100 y ¥500",
                inflacion: "2.6% (Julio  2022)",
                emisor: "Banco de Japón"
            },
            //Libra
            {
                id: "libra",
                nombre: "Libra esterlina",
                iso: "GBP",
                bandera: ":flag_gb:",
                descripcion: "La libra esterlina es la moneda oficial del Reino Unido, así como de varias dependencias y territorios británicos. Es el cuarto mayor moneda en términos de volumen de transacciones en el mercado de divisas y es considerada una de las monedas más antiguas y estables del mundo",
                color: "#9B59B6",
                gradient: ["#2a1a35", "#1a0f22"],
                gradientBox: ["#3d2850", "#2f1f40"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/913895989889359902/ReinaIsabeltest.png",
                ac: "1158",
                paises: ":flag_gb: :flag_im::flag_gg: :flag_je: :flag_fk: :flag_gi: :flag_sh: :flag_gs: :flag_io:",
                simbolo: "£",
                billetes: "5, 10, 20, 50 libras esterlinas",
                monedas: "1, 2, 5, 10, 20, 50 peniques, 1, 2 libras esterlinas",
                inflacion: "2.3%",
                emisor: "Banco de Inglaterra"
            },
            //Rublo
            {
                id: "rublo",
                nombre: "Rublo ruso",
                iso: "RUB",
                bandera: ":flag_ru:",
                descripcion: "El rublo ruso es la moneda oficial de la Federación Rusa. Fue introducido en 1992 después de la caída del sistema soviético y reemplazó al antiguo rublo soviético. El tipo de cambio del rublo respecto al dólar estadounidense ha sido volátil en los últimos años debido a factores económicos y políticos.",
                color: "#3498DB",
                gradient: ["#1a1a2a", "#0f0f1a"],
                gradientBox: ["#252540", "#1c1c32"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/920139509344108594/bancario_1.png",
                ac: "1992",
                paises: ":flag_ru:",
                simbolo: "₽",
                billetes: "5, 10, 50, 100, 500, 1000, 5000 rublos",
                monedas: "1, 2, 5, 10, 20, 50 kopeks, 1, 2, 5 rublos",
                inflacion: "5.5%",
                emisor: "Banco Central de Rusia"
            },
            //Dólar Canadiense
            {
                id: "dolarcanadiense",
                nombre: "Dólar canadiense",
                iso: "CAD",
                bandera: ":flag_ca:",
                descripcion: "El dólar canadiense es la moneda oficial de Canadá. Es ampliamente aceptado en los Estados Unidos y en otros países de América del Norte debido a la cercanía geográfica y económica con Canadá. El tipo de cambio del dólar canadiense respecto al dólar estadounidense ha fluctuado en los últimos años debido a factores económicos y políticos.",
                color: "#E74C3C",
                gradient: ["#2a1a1a", "#1a0f0f"],
                gradientBox: ["#3d2525", "#2f1c1c"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/928332562793922611/canadian-dollar.png",
                ac: "1858",
                paises: ":flag_ca:",
                simbolo: "C$",
                billetes: "5, 10, 20, 50, 100 dólares canadienses",
                monedas: "1, 5, 10, 25, 50 centavos, 1 dólar canadiense",
                inflacion: "2.5%",
                emisor: "Banco de Canadá"
            },
            {
                id: "dolaraustraliano",
                nombre: "Dólar australiano",
                iso: "AUD",
                bandera: ":flag_au:",
                descripcion: "El dólar australiano es la moneda oficial de Australia. Es ampliamente utilizado en las Islas del Pacífico y en Asia debido a la cercanía geográfica y económica con Australia. El tipo de cambio del dólar australiano respecto al dólar estadounidense ha fluctuado en los últimos años debido a factores económicos y políticos.",
                color: "#2980B9",
                gradient: ["#1a1a2a", "#0f0f1a"],
                gradientBox: ["#252545", "#1c1c35"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/858087525518934076/dolaraustraliano.png",
                ac: "1966",
                paises: ":flag_au:",
                simbolo: "A$",
                billetes: "5, 10, 20, 50, 100 dólares australianos",
                monedas: "5, 10, 20, 50 centavos, 1, 2 dólares australianos",
                inflacion: "1.7%",
                emisor: "Banco de la Reserva de Australia"
            },
            //Dólar Neozelandes
            {
                id: "dolarneozelandes",
                nombre: "Dólar neozelandés",
                iso: "NZD",
                bandera: ":flag_nz:",
                descripcion: "El dólar neozelandés es la moneda oficial de Nueva Zelanda. Es una moneda relativamente nueva, habiendo sido introducida en 1967 para reemplazar la libra neozelandesa. Es ampliamente utilizado en las transacciones comerciales y turísticas en el país.",
                color: "#1ABC9C",
                gradient: ["#1a2a28", "#0f1a18"],
                gradientBox: ["#254540", "#1c3532"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/858094221654753300/Dolar_nueva_zelanda.png",
                ac: "1967",
                paises: ":flag_nz: :flag_ck: :flag_nu: :flag_tk: :flag_pn: ",
                simbolo: "NZ$",
                billetes: "5, 10, 20, 50 y 100 dólares neozelandeses",
                monedas: "1, 2, 5, 10, 20 y 50 centavos, 1 dólar neozelandés",
                inflacion: "1.5%",
                emisor: "Banco de la Reserva de Nueva Zelanda"
            },
            //Peso Mexicano
            {
                id: "pesomexicano",
                nombre: "Peso mexicano",
                iso: "MXN",
                bandera: ":flag_mx:",
                descripcion: "El peso mexicano es la moneda oficial de México. Fue introducido en 1993 para reemplazar al antiguo peso mexicano. Es ampliamente utilizado en las transacciones comerciales y turísticas en el país.",
                color: "#27AE60",
                gradient: ["#1a2a1e", "#0f1a12"],
                gradientBox: ["#254530", "#1c3525"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/838470413066436658/MXNPeso.png",
                ac: "1993",
                paises: ":flag_mx:",
                simbolo: "$",
                billetes: "20, 50, 100, 200, 500 y 1000 pesos mexicanos",
                monedas: "5, 10, 20 y 50 centavos, 1 y 2 pesos mexicanos",
                inflacion: "3.5%",
                emisor: "Banco de México"
            },
            //Peso chileno
            {
                id: "pesochileno",
                nombre: "Peso chileno",
                iso: "CLP",
                bandera: ":flag_cl:",
                descripcion: "El peso chileno es la moneda oficial de Chile. Fue introducido en 1975 para reemplazar al antiguo peso chileno. Es ampliamente utilizado en las transacciones comerciales y turísticas en el país.",
                color: "#E74C3C",
                gradient: ["#2a1a1e", "#1a0f12"],
                gradientBox: ["#3d2530", "#2f1c25"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/856753411793354773/pesochileno.png",
                ac: "1975",
                paises: ":flag_cl:",
                simbolo: "$",
                billetes: "1000, 2000, 5000, 10000 y 20000 pesos chilenos",
                monedas: "1, 5, 10, 50 y 100 pesos chilenos",
                inflacion: "2.5%",
                emisor: "Banco Central de Chile"
            },
            //Peso uruguayo
            {
                id: "pesouruguayo",
                nombre: "Peso uruguayo",
                iso: "UYU",
                bandera: ":flag_uy:",
                descripcion: "El peso uruguayo es la moneda oficial de Uruguay. Es emitido por el Banco Central del Uruguay y su simbolo es $U. ",
                color: "#5DADE2",
                gradient: ["#1a2535", "#0f1522"],
                gradientBox: ["#253852", "#1c2d45"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/856766027831574528/pesouruguayo.png",
                ac: "1897",
                paises: ":flag_uy:",
                simbolo: "$U",
                billetes: "50, 100, 200, 500, 1000, 2000, 5000 pesos uruguayos",
                monedas: "1, 2, 5, 10, 20, 50 centesimos, 1 peso uruguayo",
                inflacion: "5.5%",
                emisor: "Banco Central del Uruguay"
            },
            //Peso colombiano
            {
                id: "pesocolombiano",
                nombre: "Peso colombiano",
                iso: "COP",
                bandera: ":flag_co:",
                descripcion: "El peso colombiano es la moneda oficial de Colombia. Es emitido por el Banco de la República de Colombia y su simbolo es $. ",
                color: "#F1C40F",
                gradient: ["#2a2515", "#1a180d"],
                gradientBox: ["#3d3820", "#2f2a18"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/857487546455294022/PesoColombiano.png",
                ac: "1837",
                paises: ":flag_co:",
                simbolo: "$",
                billetes: "1.000, 2.000, 5.000, 10.000, 20.000, 50.000, 100.000 pesos colombianos",
                monedas: "5, 10, 25, 50 centavos, 1 peso colombiano",
                inflacion: "3.7%",
                emisor: "Banco de la República de Colombia"
            },
            {
                id: "boliviano",
                nombre: "Boliviano",
                iso: "BOB",
                bandera: ":flag_bo:",
                descripcion: "El boliviano es la moneda oficial de Bolivia. Es emitido por el Banco Central de Bolivia y su simbolo es Bs. ",
                color: "#2ECC71",
                gradient: ["#1a2a1e", "#0f1a12"],
                gradientBox: ["#254530", "#1c3525"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/858355537228595201/Boliviano.png",
                ac: "1864",
                paises: ":flag_bo:",
                simbolo: "Bs",
                billetes: "2, 5, 10, 20, 50, 100 bolivianos",
                monedas: "1, 2, 5, 10 centavos, 1 boliviano",
                inflacion: "3.1%",
                emisor: "Banco Central de Bolivia"
            },
            {
                id: "sol",
                nombre: "Sol peruano",
                iso: "PEN",
                bandera: ":flag_pe:",
                descripcion: "El sol es la moneda oficial de Perú. Es emitido por el Banco Central de Reserva del Perú y su simbolo es S/. ",
                color: "#E74C3C",
                gradient: ["#2a1a1a", "#1a0f0f"],
                gradientBox: ["#3d2525", "#2f1c1c"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/1068674182201753690/SolPeruano.png",
                ac: "1991",
                paises: ":flag_pe:",
                simbolo: "S/",
                billetes: "10, 20, 50, 100, 200 soles",
                monedas: "1, 5, 10, 20, 50 céntimos, 1 sol",
                inflacion: "1.8%",
                emisor: "Banco Central de Reserva del Perú"
            },
            {
                id: "guarani",
                nombre: "Guaraní",
                iso: "PYG",
                bandera: ":flag_py:",
                descripcion: "El guaraní es la moneda oficial de Paraguay. Es emitido por el Banco Central del Paraguay y su simbolo es Gs. ",
                color: "#E74C3C",
                gradient: ["#2a1a1e", "#1a0f12"],
                gradientBox: ["#3d2530", "#2f1c25"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/856970634726735902/guaraniparaguayo.png",
                ac: "1944",
                paises: ":flag_py:",
                simbolo: "Gs",
                billetes: "2.000, 5.000, 10.000, 20.000, 50.000, 100.000 guaraníes",
                monedas: "50, 100, 500 guaraníes",
                inflacion: "2.5%",
                emisor: "Banco Central del Paraguay"
            },
            {
                id: "bolivar",
                nombre: "Bolivar Digital Venezolano",
                iso: "VED",
                bandera: ":flag_ve:",
                descripcion: "El Bolivar Digital es la moneda de curso legal de la República Bolivariana de Venezuela. Esta moneda reemplazó al Bolívar Soberano (Bs. S) que circuló desde  agosto de 2018 y octubre de 2021. El valor de la nueva moneda se obtendrá quitando seis ceros a la antigua.",
                color: "#F39C12",
                gradient: ["#2a2015", "#1a150d"],
                gradientBox: ["#3d3220", "#2f2818"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/894982507563483216/bolivardigital.png",
                ac: "1 de octubre del 2021",
                paises: ":flag_ve:",
                simbolo: "Bs",
                billetes: "5, 10, 20, 50 y 100 Bolívares.",
                monedas: "	25 Céntimos, 50 Céntimos y 1 Bolívar.",
                inflacion: "305,7% (2022)",
                emisor: "Banco Central de Venezuela"
            },
            {
                id: "yuan",
                nombre: "Yuan chino",
                iso: "CNY",
                bandera: ":flag_cn:",
                descripcion: "El yuan chino es la moneda oficial de la República Popular China. Es una de las monedas más utilizadas en el mundo y es ampliamente aceptada en todo el mundo.",
                color: "#E74C3C",
                gradient: ["#2a1a1a", "#1a0f0f"],
                gradientBox: ["#3d2525", "#2f1c1c"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/858074668015157258/yuanchino.png",
                ac: "1948",
                paises: ":flag_cn:",
                simbolo: "元 / ¥",
                billetes: "1, 2, 5, 10, 20, 50, 100 yuanes",
                monedas: "1, 2, 5 jiao, 1 yuan",
                inflacion: "2.1%",
                emisor: "Banco Popular de China"
            },
            {
                id: "rupia",
                nombre: "Rupia india",
                iso: "INR",
                bandera: ":flag_in:",
                descripcion: "La rupia india es la moneda oficial de la India. Es la moneda más ampliamente utilizada en el país y es emitida y regulada por el Banco de la Reserva de la India.",
                color: "#E67E22",
                gradient: ["#2a2015", "#1a150d"],
                gradientBox: ["#3d3020", "#2f2518"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/858105999408103424/IndiaRupia.png",
                ac: "1935",
                paises: ":flag_in:",
                simbolo: "₹",
                billetes: "5, 10, 20, 50, 100, 200, 500, 2000 rupias indias",
                monedas: "5, 10, 20, 25, 50 paisa, 1, 2, 5 rupias indias",
                inflacion: "6.2%",
                emisor: "Banco de la Reserva de la India"
            },
            {
                id: "won",
                nombre: "Won surcoreano",
                iso: "KRW",
                bandera: ":flag_kr:",
                descripcion: "El won surcoreano es la moneda oficial de Corea del Sur. Es emitido y regulado por el Banco de Corea.",
                color: "#3498DB",
                gradient: ["#1a2030", "#0f1520"],
                gradientBox: ["#253548", "#1c2838"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/858122163164807168/CoreaDelSurMoneda.png",
                ac: "1945",
                paises: ":flag_kr:",
                simbolo: "₩",
                billetes: "1000, 5000, 10,000, 50,000 won surcoreano",
                monedas: "10, 50, 100, 500 won surcoreano",
                inflacion: "1.2%",
                emisor: "Banco de Corea"
            },
            {
                id: "franco",
                nombre: "Franco suizo",
                iso: "CHF",
                bandera: ":flag_ch:",
                descripcion: "El franco suizo es la moneda oficial de Suiza. Es emitido y regulado por el Banco Nacional Suizo.",
                color: "#E74C3C",
                gradient: ["#2a1a1a", "#1a0f0f"],
                gradientBox: ["#3d2525", "#2f1c1c"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/930958502980100116/FrancoSuizo.png",
                ac: "1850",
                paises: ":flag_ch: :flag_li: :flag_it: (Campione d'Italia) :flag_de: (Büsingen am Hochrhein)",
                simbolo: "CHF",
                billetes: "10, 20, 50, 100, 200, 1000 francos suizos",
                monedas: "5, 10, 20, 50 rappen, 1, 2 francos suizos",
                inflacion: "0.2%",
                emisor: "Banco Nacional Suizo"
            },
            {
                id: "lira",
                nombre: "Lira turca",
                iso: "TRY",
                bandera: ":flag_tr:",
                descripcion: "La lira turca es la moneda oficial de Turquía. Fue introducida en 1844 y ha sido reemplazada varias veces desde entonces debido a la hiperinflación. Actualmente, es emitida por el Banco Central de Turquía.",
                color: "#E74C3C",
                gradient: ["#2a1a1e", "#1a0f12"],
                gradientBox: ["#3d2530", "#2f1c25"],
                img: "https://cdn.discordapp.com/attachments/802944543510495292/930958503399546910/liraturca.png",
                ac: "1923",
                paises: ":flag_tr: :flag_cy: (Norte)",
                simbolo: "₺",
                billetes: "5, 10, 20, 50, 100, 200 liras turcas",
                monedas: "1, 5, 10, 25, 50 kuruş, 1 lira turca",
                inflacion: "12.15%",
                emisor: "Banco Central de Turquía"
            },

        ]

export default divisas